name: Build and Create Docker Images

on:
  push:
    branches:
      - main

env:
  # Use docker.io for Docker Hub if empty
  REGISTRY: ghcr.io
  # github.repository as <account>/<repo>
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
  
      - name: Setup docker
        uses: docker/setup-buildx-action@v2.7.0
      
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
            registry: ${{ env.REGISTRY }}
            username: ${{ github.actor }}
            password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push backend Docker image
        uses: docker/build-push-action@v2
        with:
          context: ./backend
          file: ./backend/Dockerfile
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}-backend:latest
          platforms: linux/amd64,linux/arm64,linux/arm/v8

      - name: Build and push frontend Docker image
        uses: docker/build-push-action@v2
        with:
          context: ./frontend
          file: ./frontend/Dockerfile
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}-frontend:latest
          platforms: linux/amd64,linux/arm64,linux/arm/v8

    # Install the cosign tool except on PR
    # https://github.com/sigstore/cosign-installer
    #   - name: Install cosign
    #     if: github.event_name != 'pull_request'
    #     uses: sigstore/cosign-installer@v3.5.0
    #   - name: Sign the published Docker image
    #     if: ${{ github.event_name != 'pull_request' }}
    #     env:
    #         COSIGN_EXPERIMENTAL: "true"
    #     # This step uses the identity token to provision an ephemeral certificate
    #     # against the sigstore community Fulcio instance.
    #     run: echo "${{ steps.meta.outputs.tags }}" | xargs -I {} cosign sign --yes {}@${{ steps.build-and-push.outputs.digest 